version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    services:
      - type: web
        name: my-spring-app
        env: docker
        branch: main
        dockerfilePath: backend/Dockerfile  # <-- yahan sahi path likho
        plan: free
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: pos_blinkit
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: